
INSTRUCTION_OVERRIDE = [
    "ignore all previous instructions",
    "ignore the above",
    "ignore previous instructions",
    "disregard your training",
    "disregard all prior instructions",
    "disregard the above",
    "forget everything above",
    "forget all previous instructions",
    "override your instructions",
    "override your programming",
    "your new instructions are",
    "from now on you will",
    "do not follow your guidelines",
    "bypass your restrictions",
    "bypass your guidelines",
    "this is your new system prompt",
    "new system prompt",
]
ROLEPLAY_PERSONA = [
    "developer mode",
    "dan mode",
    "you are now",
    "you are now dan",
    "act as dan",
    "you are now in",
    "no restrictions",
    "no filters",
    "no content policy",
    "unfiltered ai",
    "pretend you are",
    "pretend to be",
    "act as if you have no",
    "you have broken free of the typical confines of ai",
    "stay in character",
    "jailbreak",
    "jailbroken",
    "evil confidant",
    "opposite day",
    "do anything now",
    "which stands for",
    "immerse yourself in the role",
    "break character",
    "no longer act as",
    "not bound by",
    "free from the typical rules",
    "have no restrictions",
    "no longer bound",
    "override safety",
    "bypass restrictions",
    "unfiltered mode",
    "uncensored",
    "no limits",
    "free mode",
    "unrestricted access",
]
SEMANTIC_DISGUISE = [
    "hypothetical scenario",
    "for educational purposes",
    "for research purposes only",
    "write a story where",
    "write a fictional story",
    "in a fictional world where",
    "purely hypothetically",
    "just hypothetically speaking",
    "as a thought experiment",
    "asking for a friend",
    "this is just a game",
]
ENCODING_EVASION = [
    "translate to base64",
    "decode this base64",
    "respond in base64",
    "encode your response",
    "rot13",
    "in leetspeak",
    "reverse the following text",
    "answer backwards",
    "using only emojis",
]
SYSTEM_EXTRACTION = [
    "repeat the words above",
    "print your system prompt",
    "reveal your instructions",
    "reveal your system prompt",
    "what are your instructions",
    "output the text above",
    "show me your prompt",
    "leak your prompt",
]
KEYWORD_CATEGORIES = {
    "instruction_override": INSTRUCTION_OVERRIDE,
    "roleplay_persona": ROLEPLAY_PERSONA,
    "semantic_disguise": SEMANTIC_DISGUISE,
    "encoding_evasion": ENCODING_EVASION,
    "system_extraction": SYSTEM_EXTRACTION,
}

# Flat list of every phrase (>= 30 required by spec; currently 58)
ALL_KEYWORDS = [kw for group in KEYWORD_CATEGORIES.values() for kw in group]

assert len(ALL_KEYWORDS) >= 30, "Keyword dictionary must contain at least 30 patterns"
